//! klend-indexer — Phase 0, Week 1, Day 1.
//!
//! Goal of THIS file: prove that Kamino Lend account data flows from a Solana
//! validator into our process. No decoding, no storage — just raw updates on
//! stdout. Everything else in the plan is built on top of this working.
//!
//! Pipeline position:
//!     Validator → Geyser → Yellowstone gRPC → [WE ARE HERE] → decode → ClickHouse
//!
//! `//!` (with the bang) is an *inner* doc comment: it documents the item that
//! CONTAINS it — here, the whole crate. Plain `///` documents the item that
//! FOLLOWS it. Both render into `cargo doc`.

use std::collections::HashMap;
use std::fmt;
use std::sync::LazyLock;

use sha2::{Digest, Sha256};

// `anyhow::Result<T>` is shorthand for `Result<T, anyhow::Error>`. anyhow::Error
// can absorb ANY error type that implements std::error::Error, which is why a
// single `?` below works on env errors, TLS errors and gRPC errors alike —
// three unrelated error types, one return type.
//
// `Context` is a trait. Importing it is what gives us the `.context()` method
// on Result. Trait methods are only callable when the trait is in scope.
use anyhow::{Context, Result};

// Another trait-for-its-methods import. `GeyserStream` implements `Stream`, but
// `.next()` lives on the `StreamExt` extension trait, not on `Stream` itself.
// Delete this line and `stream.next()` stops resolving — with an error message
// that does NOT obviously point back to a missing import. This is Rust's most
// common "but the method exists!" trap.
use futures::StreamExt;

use yellowstone_grpc_client::{ClientTlsConfig, GeyserGrpcClient};

// These types are generated by `prost` from the Yellowstone .proto files —
// nobody hand-wrote them. That explains two things you'll notice below:
//
//   1. `subscribe_update::UpdateOneof` sits in a lowercase submodule. A protobuf
//      `oneof` field becomes a Rust enum placed in a module named after its
//      parent message (`SubscribeUpdate` -> `subscribe_update`).
//   2. Nearly every field is `Option<T>`. protobuf 3 has no required fields, so
//      codegen must represent "absent" for all of them.
use yellowstone_grpc_proto::geyser::{
    subscribe_update::UpdateOneof, CommitmentLevel, SubscribeRequest,
    SubscribeRequestFilterAccounts,
};

/// Candidate klend account struct names.
///
/// This is a list of NAMES, not of discriminator bytes, and that is the whole
/// point. Anchor writes `sha256("account:<StructName>")[..8]` at offset 0 of
/// every account it initialises, so the discriminator is *derivable* from the
/// name — and a derived constant is structurally incapable of disagreeing with
/// its source, while a hand-transcribed one is a typo waiting to mislabel data.
/// (Same rule as `LEN = size_of::<Self>()` vs. a hand-summed field total: derive
/// the constant, never write it out.)
///
/// These names are still a GUESS — they come from klend's public struct names,
/// not from an IDL we've verified. That's deliberate and safe: a wrong guess
/// simply never matches any account on the wire, so it fails by being absent
/// from the output. It cannot mislabel a real account as something it isn't.
const CANDIDATE_ACCOUNTS: &[&str] = &[
    "Reserve",
    "Obligation",
    "LendingMarket",
    "ReferrerTokenState",
    "UserMetadata",
    "ReferrerState",
    "ShortUrl",
    "GlobalConfig",
];

/// `discriminator -> struct name`, derived once from [`CANDIDATE_ACCOUNTS`].
///
/// `LazyLock` (std, stable since 1.80) runs the initialiser on first access and
/// shares the result across threads — the standard-library replacement for the
/// old `lazy_static!` / `once_cell` crates. We can't build this at compile time
/// because sha256 isn't const-evaluable here, and we don't want to rebuild it
/// per account update: it is read on the hot path, once per message.
static DISCRIMINATORS: LazyLock<HashMap<[u8; 8], &'static str>> = LazyLock::new(|| {
    CANDIDATE_ACCOUNTS
        .iter()
        .map(|name| {
            let hash = Sha256::digest(format!("account:{name}").as_bytes());
            // The slice->array conversion cannot fail: sha256 is always 32 bytes,
            // so `[..8]` is always in range. `expect` documents that invariant
            // rather than hiding it behind a silent fallback.
            let disc: [u8; 8] = hash[..8].try_into().expect("sha256 digest is 32 bytes");
            (disc, *name)
        })
        .collect()
});

/// What an account's leading bytes tell us about its type.
///
/// Three outcomes, three *shapes* — deliberately not `Option<&str>`.
///
/// `Option` would collapse two genuinely different facts into one `None`:
/// "this account is too short to carry a discriminator" and "this is a klend
/// account whose type we haven't named yet". The second is a research finding
/// (there are four layouts under the klend owner and we've only named two of
/// them — see NOTES.md); the first would be a protocol surprise. A shared
/// `None` would let the interesting one hide inside the boring one.
///
/// Because this is an enum, every consumer gets an exhaustive `match`: the
/// compiler produces the list of places to update when a variant is added,
/// rather than us grepping for them. That is the difference between an
/// assumption checked at compile time and one checked by remembering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum AccountKind {
    /// Discriminator matched a name in [`CANDIDATE_ACCOUNTS`].
    Known(&'static str),
    /// Well-formed 8-byte tag, but not one we can name. Carries the raw bytes
    /// so the finding is actionable — an unnamed type prints as hex we can look
    /// up, instead of vanishing into a catch-all bucket.
    Unknown([u8; 8]),
    /// Fewer than 8 bytes of payload — cannot carry a discriminator at all.
    /// Not expected from an Anchor program; if this ever appears it is a real
    /// finding, which is exactly why it isn't folded into `Unknown`.
    Untagged { len: usize },
}

// `From` rather than `TryFrom`: classification is TOTAL — every possible byte
// slice lands in exactly one variant, so there is no error case to report. The
// `TryFrom`-as-dispatch-table pattern is the right shape when an unrecognised
// tag is a *failure* (an unknown instruction byte must abort). Here it isn't:
// an unknown account type is data we want to record and count, not an error to
// propagate. Using `TryFrom` would push "unknown" into an `Err` that a stray `?`
// could turn into "stream ends" — losing the finding to error handling.
impl From<&[u8]> for AccountKind {
    fn from(data: &[u8]) -> Self {
        let Some(head) = data.get(..8) else {
            return AccountKind::Untagged { len: data.len() };
        };
        let disc: [u8; 8] = head.try_into().expect("slice of exactly 8 bytes");

        match DISCRIMINATORS.get(&disc) {
            Some(name) => AccountKind::Known(name),
            None => AccountKind::Unknown(disc),
        }
    }
}

impl fmt::Display for AccountKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // ⚠️  `write!(f, ...)` here would IGNORE width and alignment: `{kind:<22}`
        // silently formats as if no width were given, because padding is applied
        // by `Formatter::pad`, not by the `{}` machinery around a custom impl.
        // The first version of this did exactly that and produced a ragged
        // summary table. Routing through `f.pad` is what makes a custom Display
        // honour the same format specs a `&str` would.
        let text = match self {
            AccountKind::Known(name) => (*name).to_owned(),
            // Prefixed so an unnamed type can never be mistaken for a named one
            // in the output, at a glance or by a downstream parser.
            AccountKind::Unknown(disc) => format!("unknown:{}", hex8(disc)),
            AccountKind::Untagged { len } => format!("untagged:{len}b"),
        };
        f.pad(&text)
    }
}

/// Lowercase hex for a discriminator. std has no hex formatter for slices, and
/// pulling a crate for eight bytes isn't worth the dependency.
fn hex8(bytes: &[u8; 8]) -> String {
    use fmt::Write as _;
    bytes.iter().fold(String::with_capacity(16), |mut s, b| {
        // Writing to a String is infallible; the Result exists only because the
        // `Write` trait is shared with fallible sinks like files and sockets.
        let _ = write!(s, "{b:02x}");
        s
    })
}

/// Kamino Lend production mainnet program ID (plan §8b).
///
/// Every obligation and reserve account is *owned* by this program, which is
/// what makes the owner filter below a clean way to say "give me all klend
/// state and nothing else".
///
/// Staging equivalent, useful for low-volume testing:
///     SLendK7ySfcEzyaFqy93gDnD3RtrpXJcnRwb6zFHJSh
const KLEND_PROGRAM: &str = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD";

// `#[tokio::main]` is a macro that rewrites this async fn into a normal sync
// `main` which spins up a Tokio runtime and blocks on our future. Rust ships no
// async executor in std — you must bring one. (Enabled by tokio's "full" feature.)
//
// Returning `Result<()>` is what lets us use `?` inside main. On an Err, Rust
// prints the Debug form and exits nonzero; with anyhow that Debug form includes
// the whole `.context()` chain, newest first.
#[tokio::main]
async fn main() -> Result<()> {
    // ---------------------------------------------------------------------
    // 0. TLS BACKEND — must happen before any TLS is constructed.
    // ---------------------------------------------------------------------
    // rustls 0.23 does NOT pick a cryptography backend for you. It expects
    // exactly one of the `ring` / `aws_lc_rs` features to be enabled somewhere
    // in the build, and panics at first use if it finds zero or two.
    //
    // We hit the ZERO case: something upstream (tonic -> tokio-rustls) depends
    // on rustls with default-features = false, which strips the provider out,
    // and yellowstone-grpc-client exposes no feature knob to put one back. So
    // this crate declares `ring` directly in Cargo.toml.
    //
    // Chose `ring` over `aws_lc_rs` because the latter pulls in aws-lc-sys,
    // which needs cmake and a C toolchain — avoidable pain on macOS.
    //
    // With exactly one feature enabled rustls CAN auto-select, so strictly this
    // call is redundant today. It is here on purpose: if a future dependency
    // ever enables the other backend, auto-selection silently becomes ambiguous
    // again and we'd be back to a runtime panic. This makes the choice explicit
    // and keeps the failure at startup rather than at first connection.
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("failed to install rustls crypto provider");

    // ---------------------------------------------------------------------
    // 1. CONFIG — never hardcode the API key.
    // ---------------------------------------------------------------------
    // Alchemy specifics (verified against their gRPC quickstart):
    //   GRPC_URL   = https://solana-mainnet.g.alchemy.com   <- bare host, NO path
    //   GRPC_TOKEN = the API key, sent as the x-token HEADER, not in the URL
    //
    // Why `.context()` matters: a bare `std::env::var("GRPC_URL")?` fails with
    // the string "environment variable not found" and does NOT say WHICH
    // variable. With two of them, that is genuinely ambiguous at 2am. `.context()`
    // keeps the original cause and prepends something useful.
    let url = std::env::var("GRPC_URL")
        .context("GRPC_URL not set — export the Alchemy endpoint first")?;
    let token = std::env::var("GRPC_TOKEN")
        .context("GRPC_TOKEN not set — export your Alchemy API key first")?;

    // ---------------------------------------------------------------------
    // 2. CONNECT — a builder chain where every step can fail.
    // ---------------------------------------------------------------------
    // Hence a `?` on almost every line. What each step can fail on:
    //   build_from_shared -> the URL doesn't parse
    //   x_token           -> key isn't a legal HTTP header value (a trailing
    //                        newline from a copy-paste is caught right here)
    //   tls_config        -> OS root certificate store won't load
    //   connect           -> DNS / TCP / TLS handshake / HTTP2 negotiation
    //
    // `mut` is required because `subscribe_with_request` takes `&mut self`.
    let mut client = GeyserGrpcClient::build_from_shared(url)?
        .x_token(Some(token))?
        .tls_config(ClientTlsConfig::new().with_native_roots())?
        .connect()
        .await?;

    // ---------------------------------------------------------------------
    // 3. THE FILTER — the most consequential block in this file.
    // ---------------------------------------------------------------------
    // Filters arrive as a MAP, not a list. The key ("klend") is a label we
    // invent; the server echoes it back on every matching update, so one
    // subscription can carry several independently-named filters and we can
    // route on the label later. We have exactly one today.
    let mut accounts = HashMap::new();
    accounts.insert(
        "klend".to_owned(),
        SubscribeRequestFilterAccounts {
            // "every account whose owner field == the klend program" — i.e. all
            // obligations and reserves, and nothing else on the chain.
            owner: vec![KLEND_PROGRAM.to_owned()],

            // ⚠️  MONEY SAFETY (plan §7d):
            // An EMPTY owner vec is not "no accounts" — it is "no filter", which
            // subscribes us to every account update on mainnet. Under Alchemy's
            // usage-based ~$75/TB pricing that is a financial event, not just a
            // bug, and it fails silently (data still flows; the bill arrives later).
            // Never let this vec become empty.
            //
            // `..Default::default()` fills the remaining fields (account, filters,
            // nonempty_txn_signature). Two reasons to prefer it over listing them:
            // it survives a minor version adding a new field, and it keeps the
            // owner line visually isolated so the safety-critical bit stands out.
            //
            // Later (once decode is stable) two more fields live here:
            //   filters             -> memcmp on the Anchor discriminator, to split
            //                          Obligation from Reserve server-side
            //   accounts_data_slice -> trim payloads to the byte ranges we need,
            //                          a direct lever on the bandwidth bill (§8b)
            ..Default::default()
        },
    );

    let request = SubscribeRequest {
        accounts,

        // Commitment is `Option<i32>`, not `Option<CommitmentLevel>` — protobuf
        // enums are transmitted as plain integers, so codegen exposes an i32 and
        // we cast. An unknown integer is therefore representable, which is why
        // this can't be a plain Rust enum.
        //
        // CONFIRMED = supermajority voted, not yet finalized. The deliberate
        // middle choice: PROCESSED is faster but gets rolled back on forks,
        // FINALIZED is ~13s behind. Fork handling in Phase 1 is exactly the work
        // of dealing with what CONFIRMED can still take back.
        commitment: Some(CommitmentLevel::Confirmed as i32),

        // Unused-for-now fields include: slots, transactions, blocks, and
        // `from_slot` (replay, capped at ~6000 slots ≈ 40 min — a crash-recovery
        // buffer, NOT a backfill mechanism; see §8c).
        ..Default::default()
    };

    // ---------------------------------------------------------------------
    // 4. SUBSCRIBE
    // ---------------------------------------------------------------------
    // ⚠️  `_sink` and `_` are NOT the same thing.
    //   `_`     discards the value immediately and runs its destructor NOW.
    //   `_sink` binds it to a (conventionally unused) name, keeping it alive
    //           until the end of scope.
    // The sink owns our half of the bidirectional gRPC stream. Drop it and the
    // server may tear the subscription down — producing a stream that simply
    // ends, with no error, for no visible reason. Renaming this to `_` is a real
    // bug that costs an hour. The underscore prefix only silences the
    // unused-variable warning; it does not change drop timing.
    let (_sink, mut stream) = client.subscribe_with_request(Some(request)).await?;

    // Logs to stderr, DATA to stdout (the println! below). Deliberate discipline:
    // it means `cargo run > sample.jsonl` captures clean records while status
    // still shows in the terminal. You'll want that within a few days.
    eprintln!("subscribed to klend {KLEND_PROGRAM}; waiting for updates…");

    // ---------------------------------------------------------------------
    // 4b. SAMPLE BUDGET — the fix for day 1's orphaned-process incident.
    // ---------------------------------------------------------------------
    // Day 1 tried to time-box a run from OUTSIDE (`alarm N; exec ./run.sh`).
    // That killed run.sh and cargo, but `cargo run` execs the binary as a child
    // that OUTLIVED its parent: two orphans streamed billable data for ~19 and
    // ~9 minutes after being "stopped", and corrupted two measurements.
    //
    // The robust fix is for the process to bound ITSELF. No signal to deliver,
    // no process group to get wrong, nothing to survive.
    //
    // Budget is in SLOTS, not seconds, for the second day-1 lesson: derive
    // elapsed time from the DATA, not the wall clock. Slots advance at ~400 ms
    // and are produced by the chain, so a slot-counted sample is immune to the
    // very class of error that corrupted the first measurement. Unset = run
    // forever, which is the eventual 24/7 mode (§7d).
    let slot_budget: Option<u64> = match std::env::var("KLEND_SAMPLE_SLOTS") {
        Ok(raw) => Some(
            raw.parse()
                // A malformed budget must ABORT, never silently fall back to
                // "run forever" — on a bandwidth-billed stream, a fallback that
                // looks like success is a financial event, not a typo.
                .with_context(|| format!("KLEND_SAMPLE_SLOTS must be a slot count, got {raw:?}"))?,
        ),
        Err(_) => None,
    };

    // Tally keyed by (kind, data_len): the pairing is the actual research
    // question. Keying on kind alone would hide a type with two layouts (a
    // versioned struct); on len alone it would merge two types that happen to
    // share a size — which is precisely the inference day 1 could not rule out.
    let mut tally: HashMap<(AccountKind, usize), u64> = HashMap::new();
    let mut total_bytes: u64 = 0;
    let mut first_slot: Option<u64> = None;
    let mut last_slot: u64 = 0;

    // TWO DIFFERENT QUANTITIES, deliberately not sharing the word "slots".
    //
    // The first sample run conflated them and the budget silently meant
    // something ~25x longer than intended:
    //
    //   slot SPAN            = last_slot - first_slot. Chain time. The clock.
    //   slots WITH UPDATES   = slots carrying >=1 klend update. A finding.
    //
    // They are wildly different because klend updates are bursty, not
    // per-slot: the first run saw 18 slots-with-updates across a 456-slot
    // span. Budgeting on the second means "150 slots" buys 150 *active* slots
    // — an unbounded and unpredictable amount of real time, on a
    // bandwidth-billed stream. Only the span is a clock.
    let mut slots_with_updates: u64 = 0;

    // ---------------------------------------------------------------------
    // 5. THE STREAM LOOP
    // ---------------------------------------------------------------------
    // `.next()` yields Option<...>: `Some` per message, `None` when the stream
    // ends for good. `.await` parks this task without blocking the thread.
    while let Some(message) = stream.next().await {
        // Each item is itself a Result — a gRPC stream can fail MID-stream, not
        // only at connect time. Today `?` exits the loop on any transport error.
        //
        // That is correct for day 1 and WRONG by week 2: this exact line is where
        // §8c's reconnect-and-resume goes (persist last_processed_slot, compute
        // gap on restart, resume via from_slot if under ~5500 slots, else record
        // the gap and backfill from archives). It is also the answer to the Lane A
        // interview question "your stream drops — where do you resume?".
        let message = message?; // TODO(wk2): reconnect + resume from last slot (§8c)

        // `update_oneof` is the protobuf oneof: exactly one variant is set,
        // telling us which KIND of update arrived (account / slot / block / ping…).
        match message.update_oneof {
            Some(UpdateOneof::Account(update)) => {
                // let-else (stable since 1.65): bind `info` in THIS scope if the
                // Option is Some, otherwise take the early exit. Compare with
                // `if let Some(info) = ... { }`, which would indent everything
                // that follows. let-else keeps the happy path flat.
                //
                // The Option exists because protobuf 3 has no required fields —
                // "an account update with no account" is representable on the
                // wire even though it should never occur in practice.
                let Some(info) = update.account else { continue };

                // Classify BEFORE printing: the type tag is now the primary
                // field of a record, not an afterthought appended to it.
                let kind = AccountKind::from(info.data.as_slice());

                *tally.entry((kind, info.data.len())).or_insert(0) += 1;
                total_bytes += info.data.len() as u64;

                // Slot accounting. Updates arrive in slot order, so a change in
                // `update.slot` marks a slot boundary — no set of seen slots to
                // keep in memory, which matters for a process meant to run for
                // months rather than minutes.
                if first_slot.is_none() {
                    first_slot = Some(update.slot);
                    slots_with_updates = 1;
                } else if update.slot != last_slot {
                    slots_with_updates += 1;
                }
                last_slot = update.slot;

                // The clock: chain slots elapsed since the first update.
                let slot_span = last_slot.saturating_sub(first_slot.unwrap_or(last_slot));

                println!(
                    "slot={} pubkey={} kind={kind} data_len={} write_version={}",
                    // Which slot this state belongs to. Under CONFIRMED this can
                    // still be rolled back by a fork.
                    update.slot,
                    // `info.pubkey` is Vec<u8> — 32 RAW bytes, not text. bs58 is
                    // the encoding that produces the address form you'd paste into
                    // an explorer. Cheap to skip today, but unreadable if you do.
                    bs58::encode(&info.pubkey).into_string(),
                    // Account payload size. Watch this column: a MIX of sizes
                    // means we're seeing both Obligation and Reserve accounts,
                    // which is what motivates the discriminator memcmp filter and
                    // sets up the day-3 decode work.
                    info.data.len(),
                    // The idempotency key (§8b). A monotonic counter that
                    // disambiguates multiple writes to the SAME account within the
                    // SAME slot. Printing it now because it becomes part of the
                    // ReplacingMergeTree ORDER BY in week 2 — dedup for free.
                    info.write_version,
                );

                // Self-imposed stop. Breaking (not `return`) means the summary
                // below runs on the sampling path too — a sample that ends
                // without reporting what it measured is a wasted spend.
                if slot_budget.is_some_and(|budget| slot_span >= budget) {
                    eprintln!("slot budget reached (span {slot_span}); stopping");
                    break;
                }
            }

            // Keepalive. The server pings to hold the connection open through
            // idle periods and NAT timeouts. Nothing to do, but it must be
            // matched or it falls to `_` below — harmless here, but worth seeing
            // explicitly so the connection's liveness behaviour is visible.
            Some(UpdateOneof::Ping(_)) => {}

            // Slot / block / transaction / entry updates we didn't subscribe to,
            // plus `None` if a future server sends a variant this build predates.
            _ => {}
        }
    }

    // ---------------------------------------------------------------------
    // 6. SUMMARY — to stderr, so it never pollutes a captured stdout sample.
    // ---------------------------------------------------------------------
    // Reached when the slot budget is hit, or when the stream ends cleanly.
    // After week 2's reconnect work the second case should be nearly
    // unreachable, because the indexer is meant to run 24/7 from then on (§7d).
    let total_updates: u64 = tally.values().sum();
    let slot_span = last_slot.saturating_sub(first_slot.unwrap_or(last_slot));
    let elapsed_secs = slot_span as f64 * 0.4;

    eprintln!("\n─── sample summary ───");
    eprintln!(
        "slots {}..{} — span {slot_span} (~{elapsed_secs:.0}s chain time)",
        first_slot.unwrap_or(0),
        last_slot,
    );
    // Reported separately, and as a ratio, because the gap between these two is
    // itself the finding: it says how bursty klend writes are.
    let density = if slot_span == 0 {
        0.0
    } else {
        100.0 * slots_with_updates as f64 / slot_span as f64
    };
    eprintln!("{slots_with_updates} slots carried updates ({density:.1}% of span)");
    eprintln!("{total_updates} updates, {total_bytes} payload bytes");
    if elapsed_secs > 0.0 {
        eprintln!(
            "~{:.1} KB/s payload (bandwidth is what Alchemy bills — §8d)",
            total_bytes as f64 / 1024.0 / elapsed_secs
        );
    }

    // Sort by frequency so the dominant type is the first thing read — the
    // reserve-churn ratio is the finding that drives the whole cost argument.
    let mut rows: Vec<_> = tally.into_iter().collect();
    rows.sort_by_key(|&((kind, len), count)| (std::cmp::Reverse(count), kind, len));

    eprintln!("{:<22} {:>9} {:>8} {:>7}", "kind", "data_len", "updates", "share");
    for ((kind, len), count) in rows {
        let share = if total_updates == 0 {
            0.0
        } else {
            100.0 * count as f64 / total_updates as f64
        };
        eprintln!("{kind:<22} {len:>9} {count:>8} {share:>6.2}%");
    }

    Ok(())
}
