//! klend-indexer — Phase 0, Week 1, Day 1.
//!
//! Goal of THIS file: prove that Kamino Lend account data flows from a Solana
//! validator into our process. No decoding, no storage — just raw updates on
//! stdout. Everything else in the plan is built on top of this working.
//!
//! Pipeline position:
//!     Validator → Geyser → Yellowstone gRPC → [WE ARE HERE] → decode → ClickHouse
//!
//! `//!` (with the bang) is an *inner* doc comment: it documents the item that
//! CONTAINS it — here, the whole crate. Plain `///` documents the item that
//! FOLLOWS it. Both render into `cargo doc`.

use std::collections::HashMap;

// `anyhow::Result<T>` is shorthand for `Result<T, anyhow::Error>`. anyhow::Error
// can absorb ANY error type that implements std::error::Error, which is why a
// single `?` below works on env errors, TLS errors and gRPC errors alike —
// three unrelated error types, one return type.
//
// `Context` is a trait. Importing it is what gives us the `.context()` method
// on Result. Trait methods are only callable when the trait is in scope.
use anyhow::{Context, Result};

// Another trait-for-its-methods import. `GeyserStream` implements `Stream`, but
// `.next()` lives on the `StreamExt` extension trait, not on `Stream` itself.
// Delete this line and `stream.next()` stops resolving — with an error message
// that does NOT obviously point back to a missing import. This is Rust's most
// common "but the method exists!" trap.
use futures::StreamExt;

use yellowstone_grpc_client::{ClientTlsConfig, GeyserGrpcClient};

// These types are generated by `prost` from the Yellowstone .proto files —
// nobody hand-wrote them. That explains two things you'll notice below:
//
//   1. `subscribe_update::UpdateOneof` sits in a lowercase submodule. A protobuf
//      `oneof` field becomes a Rust enum placed in a module named after its
//      parent message (`SubscribeUpdate` -> `subscribe_update`).
//   2. Nearly every field is `Option<T>`. protobuf 3 has no required fields, so
//      codegen must represent "absent" for all of them.
use yellowstone_grpc_proto::geyser::{
    subscribe_update::UpdateOneof, CommitmentLevel, SubscribeRequest,
    SubscribeRequestFilterAccounts,
};

/// Kamino Lend production mainnet program ID (plan §8b).
///
/// Every obligation and reserve account is *owned* by this program, which is
/// what makes the owner filter below a clean way to say "give me all klend
/// state and nothing else".
///
/// Staging equivalent, useful for low-volume testing:
///     SLendK7ySfcEzyaFqy93gDnD3RtrpXJcnRwb6zFHJSh
const KLEND_PROGRAM: &str = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD";

// `#[tokio::main]` is a macro that rewrites this async fn into a normal sync
// `main` which spins up a Tokio runtime and blocks on our future. Rust ships no
// async executor in std — you must bring one. (Enabled by tokio's "full" feature.)
//
// Returning `Result<()>` is what lets us use `?` inside main. On an Err, Rust
// prints the Debug form and exits nonzero; with anyhow that Debug form includes
// the whole `.context()` chain, newest first.
#[tokio::main]
async fn main() -> Result<()> {
    // ---------------------------------------------------------------------
    // 0. TLS BACKEND — must happen before any TLS is constructed.
    // ---------------------------------------------------------------------
    // rustls 0.23 does NOT pick a cryptography backend for you. It expects
    // exactly one of the `ring` / `aws_lc_rs` features to be enabled somewhere
    // in the build, and panics at first use if it finds zero or two.
    //
    // We hit the ZERO case: something upstream (tonic -> tokio-rustls) depends
    // on rustls with default-features = false, which strips the provider out,
    // and yellowstone-grpc-client exposes no feature knob to put one back. So
    // this crate declares `ring` directly in Cargo.toml.
    //
    // Chose `ring` over `aws_lc_rs` because the latter pulls in aws-lc-sys,
    // which needs cmake and a C toolchain — avoidable pain on macOS.
    //
    // With exactly one feature enabled rustls CAN auto-select, so strictly this
    // call is redundant today. It is here on purpose: if a future dependency
    // ever enables the other backend, auto-selection silently becomes ambiguous
    // again and we'd be back to a runtime panic. This makes the choice explicit
    // and keeps the failure at startup rather than at first connection.
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("failed to install rustls crypto provider");

    // ---------------------------------------------------------------------
    // 1. CONFIG — never hardcode the API key.
    // ---------------------------------------------------------------------
    // Alchemy specifics (verified against their gRPC quickstart):
    //   GRPC_URL   = https://solana-mainnet.g.alchemy.com   <- bare host, NO path
    //   GRPC_TOKEN = the API key, sent as the x-token HEADER, not in the URL
    //
    // Why `.context()` matters: a bare `std::env::var("GRPC_URL")?` fails with
    // the string "environment variable not found" and does NOT say WHICH
    // variable. With two of them, that is genuinely ambiguous at 2am. `.context()`
    // keeps the original cause and prepends something useful.
    let url = std::env::var("GRPC_URL")
        .context("GRPC_URL not set — export the Alchemy endpoint first")?;
    let token = std::env::var("GRPC_TOKEN")
        .context("GRPC_TOKEN not set — export your Alchemy API key first")?;

    // ---------------------------------------------------------------------
    // 2. CONNECT — a builder chain where every step can fail.
    // ---------------------------------------------------------------------
    // Hence a `?` on almost every line. What each step can fail on:
    //   build_from_shared -> the URL doesn't parse
    //   x_token           -> key isn't a legal HTTP header value (a trailing
    //                        newline from a copy-paste is caught right here)
    //   tls_config        -> OS root certificate store won't load
    //   connect           -> DNS / TCP / TLS handshake / HTTP2 negotiation
    //
    // `mut` is required because `subscribe_with_request` takes `&mut self`.
    let mut client = GeyserGrpcClient::build_from_shared(url)?
        .x_token(Some(token))?
        .tls_config(ClientTlsConfig::new().with_native_roots())?
        .connect()
        .await?;

    // ---------------------------------------------------------------------
    // 3. THE FILTER — the most consequential block in this file.
    // ---------------------------------------------------------------------
    // Filters arrive as a MAP, not a list. The key ("klend") is a label we
    // invent; the server echoes it back on every matching update, so one
    // subscription can carry several independently-named filters and we can
    // route on the label later. We have exactly one today.
    let mut accounts = HashMap::new();
    accounts.insert(
        "klend".to_owned(),
        SubscribeRequestFilterAccounts {
            // "every account whose owner field == the klend program" — i.e. all
            // obligations and reserves, and nothing else on the chain.
            owner: vec![KLEND_PROGRAM.to_owned()],

            // ⚠️  MONEY SAFETY (plan §7d):
            // An EMPTY owner vec is not "no accounts" — it is "no filter", which
            // subscribes us to every account update on mainnet. Under Alchemy's
            // usage-based ~$75/TB pricing that is a financial event, not just a
            // bug, and it fails silently (data still flows; the bill arrives later).
            // Never let this vec become empty.
            //
            // `..Default::default()` fills the remaining fields (account, filters,
            // nonempty_txn_signature). Two reasons to prefer it over listing them:
            // it survives a minor version adding a new field, and it keeps the
            // owner line visually isolated so the safety-critical bit stands out.
            //
            // Later (once decode is stable) two more fields live here:
            //   filters             -> memcmp on the Anchor discriminator, to split
            //                          Obligation from Reserve server-side
            //   accounts_data_slice -> trim payloads to the byte ranges we need,
            //                          a direct lever on the bandwidth bill (§8b)
            ..Default::default()
        },
    );

    let request = SubscribeRequest {
        accounts,

        // Commitment is `Option<i32>`, not `Option<CommitmentLevel>` — protobuf
        // enums are transmitted as plain integers, so codegen exposes an i32 and
        // we cast. An unknown integer is therefore representable, which is why
        // this can't be a plain Rust enum.
        //
        // CONFIRMED = supermajority voted, not yet finalized. The deliberate
        // middle choice: PROCESSED is faster but gets rolled back on forks,
        // FINALIZED is ~13s behind. Fork handling in Phase 1 is exactly the work
        // of dealing with what CONFIRMED can still take back.
        commitment: Some(CommitmentLevel::Confirmed as i32),

        // Unused-for-now fields include: slots, transactions, blocks, and
        // `from_slot` (replay, capped at ~6000 slots ≈ 40 min — a crash-recovery
        // buffer, NOT a backfill mechanism; see §8c).
        ..Default::default()
    };

    // ---------------------------------------------------------------------
    // 4. SUBSCRIBE
    // ---------------------------------------------------------------------
    // ⚠️  `_sink` and `_` are NOT the same thing.
    //   `_`     discards the value immediately and runs its destructor NOW.
    //   `_sink` binds it to a (conventionally unused) name, keeping it alive
    //           until the end of scope.
    // The sink owns our half of the bidirectional gRPC stream. Drop it and the
    // server may tear the subscription down — producing a stream that simply
    // ends, with no error, for no visible reason. Renaming this to `_` is a real
    // bug that costs an hour. The underscore prefix only silences the
    // unused-variable warning; it does not change drop timing.
    let (_sink, mut stream) = client.subscribe_with_request(Some(request)).await?;

    // Logs to stderr, DATA to stdout (the println! below). Deliberate discipline:
    // it means `cargo run > sample.jsonl` captures clean records while status
    // still shows in the terminal. You'll want that within a few days.
    eprintln!("subscribed to klend {KLEND_PROGRAM}; waiting for updates…");

    // ---------------------------------------------------------------------
    // 5. THE STREAM LOOP
    // ---------------------------------------------------------------------
    // `.next()` yields Option<...>: `Some` per message, `None` when the stream
    // ends for good. `.await` parks this task without blocking the thread.
    while let Some(message) = stream.next().await {
        // Each item is itself a Result — a gRPC stream can fail MID-stream, not
        // only at connect time. Today `?` exits the loop on any transport error.
        //
        // That is correct for day 1 and WRONG by week 2: this exact line is where
        // §8c's reconnect-and-resume goes (persist last_processed_slot, compute
        // gap on restart, resume via from_slot if under ~5500 slots, else record
        // the gap and backfill from archives). It is also the answer to the Lane A
        // interview question "your stream drops — where do you resume?".
        let message = message?; // TODO(wk2): reconnect + resume from last slot (§8c)

        // `update_oneof` is the protobuf oneof: exactly one variant is set,
        // telling us which KIND of update arrived (account / slot / block / ping…).
        match message.update_oneof {
            Some(UpdateOneof::Account(update)) => {
                // let-else (stable since 1.65): bind `info` in THIS scope if the
                // Option is Some, otherwise take the early exit. Compare with
                // `if let Some(info) = ... { }`, which would indent everything
                // that follows. let-else keeps the happy path flat.
                //
                // The Option exists because protobuf 3 has no required fields —
                // "an account update with no account" is representable on the
                // wire even though it should never occur in practice.
                let Some(info) = update.account else { continue };

                println!(
                    "slot={} pubkey={} data_len={} write_version={}",
                    // Which slot this state belongs to. Under CONFIRMED this can
                    // still be rolled back by a fork.
                    update.slot,
                    // `info.pubkey` is Vec<u8> — 32 RAW bytes, not text. bs58 is
                    // the encoding that produces the address form you'd paste into
                    // an explorer. Cheap to skip today, but unreadable if you do.
                    bs58::encode(&info.pubkey).into_string(),
                    // Account payload size. Watch this column: a MIX of sizes
                    // means we're seeing both Obligation and Reserve accounts,
                    // which is what motivates the discriminator memcmp filter and
                    // sets up the day-3 decode work.
                    info.data.len(),
                    // The idempotency key (§8b). A monotonic counter that
                    // disambiguates multiple writes to the SAME account within the
                    // SAME slot. Printing it now because it becomes part of the
                    // ReplacingMergeTree ORDER BY in week 2 — dedup for free.
                    info.write_version,
                );
            }

            // Keepalive. The server pings to hold the connection open through
            // idle periods and NAT timeouts. Nothing to do, but it must be
            // matched or it falls to `_` below — harmless here, but worth seeing
            // explicitly so the connection's liveness behaviour is visible.
            Some(UpdateOneof::Ping(_)) => {}

            // Slot / block / transaction / entry updates we didn't subscribe to,
            // plus `None` if a future server sends a variant this build predates.
            _ => {}
        }
    }

    // Reached only when the stream ends cleanly. Today that means the process
    // exits; after week 2's reconnect work it should be nearly unreachable,
    // because the indexer is meant to run 24/7 from then on (§7d).
    Ok(())
}
